
--
-- Volcado de datos para la tabla `produccion`
--

INSERT INTO `produccion` (`pk_id_produccion`, `nombre_produccion`) VALUES
(1, 'Warner Bros'),
(2, 'Walt Disney'),
(3, 'Paramount Pictures'),
(4, 'Amazon Studios'),
(5, 'Columbia Pictures'),
(6, 'ADS Service'),
(7, '20th Century Fox'),
(8, 'Marvel Studios'),
(9, 'Universal Pictures'),
(10, 'Bainet Taldea'),
(11, 'Metro-Goldwyn-Mayer'),
(12, 'TriStar Pictures'),
(13, 'New Line Cinema'),
(14, 'Republic Pictures'),
(15, 'Touchstone Pictures'),
(16, 'Roxbury Productions'),
(17, 'Miramax'),
(18, 'Dovemead Films'),
(19, 'United Artists'),
(20, 'Orion Pictures'),
(21, 'Thorn EMI Screen Entertainment'),
(22, 'Legendary Pictures'),
(23, 'Summit Entertainment'),
(24, 'Dino de Laurentiis'),
(25, 'Lionsgate'),
(26, 'Produzioni Europee Associati'),
(27, 'Constantin Film'),
(28, 'Polygram Filmed Entertainment'),
(29, 'Atmosphere Entertainment MM'),
(30, 'Relativity Studios'),
(31, 'FilmDistrict'),
(32, 'Michael London Productions'),
(33, 'Sony Pictures'),
(34, 'Coproducción Reino Unido-Estados Unidos'),
(35, 'DreamWorks Animation'),
(36, 'Telecinco Cinema'),
(37, 'Lucasfilm'),
(38, 'Konigsberg/Sanitsky Company'),
(39, 'Studio Ghibli'),
(40, 'Monumental Pictures');
