
--
-- Volcado de datos para la tabla `director`
--

INSERT INTO `director` (`pk_id_director`, `nombre_director`, `foto_director`, `edad_director`, `fecha_nacimiento_director`, `nacionalidad_director`, `oscar_director`, `director_fallecido`, `sexo`) VALUES
(1, 'Nancy Meyers', 'img/generica.png', 75, NULL, 'USA', 'N', NULL, 'Mujer'),
(2, 'James Mangold', 'img/generica.png', 59, NULL, 'USA', 'N', NULL, 'Hombre'),
(3, 'Joseph Kosinski', 'img/generica.png', 49, NULL, 'USA', 'N', NULL, 'Hombre'),
(4, 'Jonathan Goldstein', 'img/generica.png', 58, NULL, 'USA', 'N', NULL, 'Hombre'),
(5, 'Aaron Sorkin', 'img/generica.png', 61, NULL, 'USA', 'S', NULL, 'Hombre'),
(6, 'Robert Rodriguez', 'img/generica.png', 54, NULL, 'USA', 'N', NULL, 'Hombre'),
(7, 'Santiago Segura', 'img/generica.png', 56, NULL, 'España', 'N', NULL, 'Hombre'),
(8, 'Ridley Scott', 'img/generica.png', 85, NULL, 'UK', 'S', NULL, 'Hombre'),
(9, 'Steven Spielberg', 'img/generica.png', 76, NULL, 'USA', 'S', NULL, 'Hombre'),
(10, 'Joss Whedon', 'img/generica.png', 58, NULL, 'USA', 'N', NULL, 'Hombre'),
(11, 'Fred Zinnemann', 'img/generica.png', 89, NULL, 'USA', 'S', NULL, 'Hombre'),
(12, 'Paul Urkijo Alijo', 'img/generica.png', 38, NULL, 'España', 'N', NULL, 'Hombre'),
(13, 'Cary Fukunaga', 'img/generica.png', 45, NULL, 'USA', 'N', NULL, 'Hombre'),
(14, 'Sam Mendes', 'img/generica.png', 57, NULL, 'UK', 'S', NULL, 'Hombre'),
(15, 'Martin Campbell', 'img/generica.png', 79, NULL, 'Nueva Zelanda', 'N', NULL, 'Hombre'),
(16, 'Neill Blomkamp', 'img/generica.png', 43, NULL, 'Canadá', 'N', NULL, 'Hombre'),
(17, 'Peter Jackson', 'img/generica.png', 61, NULL, 'Nueva Zelanda', 'S', NULL, 'Hombre'),
(18, 'David Lean', 'img/generica.png', 83, NULL, 'UK', 'S', 'S', 'Hombre'),
(19, 'Tony Scott', 'img/generica.png', 68, NULL, 'USA', 'N', NULL, 'Hombre'),
(20, 'F. Gary Gray', 'img/generica.png', 52, NULL, 'USA', 'N', NULL, 'Hombre'),
(21, 'Christopher Nolan', 'img/generica.png', 52, NULL, 'UK', 'N', NULL, 'Hombre'),
(22, 'John Ford', 'img/generica.png', 79, NULL, 'USA', 'S', 'S', 'Hombre'),
(23, 'Matt Reeves', 'img/generica.png', 57, NULL, 'USA', 'N', NULL, 'Hombre'),
(24, 'James Cameron', 'img/generica.png', 68, NULL, 'Canadá', 'S', NULL, 'Hombre'),
(25, 'Sam Raimi', 'img/generica.png', 63, NULL, 'USA', 'N', NULL, 'Hombre'),
(26, 'Neil Marshall', 'img/generica.png', 53, NULL, 'UK', 'N', NULL, 'Hombre'),
(27, 'John McTiernan', 'img/generica.png', 72, NULL, 'USA', 'N', NULL, 'Hombre'),
(28, 'Mark Robson', 'img/generica.png', 64, NULL, 'Canadá', 'N', 'S', 'Hombre'),
(29, 'Peter Weir', 'img/generica.png', 78, NULL, 'Australia', 'N', NULL, 'Hombre'),
(30, 'Gus Van Sant', 'img/generica.png', 70, NULL, 'USA', 'N', NULL, 'Hombre'),
(31, 'Ron Howard', 'img/generica.png', 69, NULL, 'USA', 'S', NULL, 'Hombre'),
(32, 'George Lucas', 'img/generica.png', 79, NULL, 'USA', 'N', NULL, 'Hombre'),
(33, 'John Milius', 'img/generica.png', 79, NULL, 'USA', 'N', NULL, 'Hombre'),
(34, 'David Yates', 'img/generica.png', 59, NULL, 'UK', 'N', NULL, 'Hombre'),
(35, 'Richard Donner', 'img/generica.png', 91, NULL, 'USA', 'N', 'S', 'Hombre'),
(36, 'Sylvester Stallone', 'img/generica.png', 76, NULL, 'USA', 'N', NULL, 'Hombre'),
(37, 'Gore Verbinski', 'img/generica.png', 59, NULL, 'USA', 'S', NULL, 'Hombre'),
(38, 'Kevin Costner', 'img/generica.png', 68, NULL, 'USA', 'S', NULL, 'Hombre'),
(39, 'Don Coscarelli', 'img/generica.png', 69, NULL, 'USA', 'N', NULL, 'Hombre'),
(40, 'Antoine Fuqua', 'img/generica.png', 58, NULL, 'USA', 'N', NULL, 'Hombre'),
(41, 'Guillermo del Toro', 'img/generica.png', 58, NULL, 'México', 'S', NULL, 'Hombre'),
(42, 'Kenneth Branagh', 'img/generica.png', 63, NULL, 'UK', 'S', NULL, 'Hombre'),
(43, 'Guy Ritchie', 'img/generica.png', 59, NULL, 'UK', 'N', NULL, 'Hombre'),
(44, 'Russell Mulcahy', 'img/generica.png', 70, NULL, 'Australia', 'N', NULL, 'Hombre'),
(45, 'Stephen Hopkins', 'img/generica.png', 65, NULL, 'Jamaica', 'N', NULL, 'Hombre'),
(46, 'Kevin Reynolds', 'img/generica.png', 71, NULL, 'USA', 'N', NULL, 'Hombre'),
(47, 'Denis Villeneuve', 'img/generica.png', 56, NULL, 'Canadá', 'N', NULL, 'Hombre'),
(48, 'Stephen Sommers', 'img/generica.png', 61, NULL, 'USA', 'N', NULL, 'Hombre'),
(49, 'Irvin Kershner', 'img/generica.png', 87, NULL, 'USA', 'N', 'S', 'Hombre'),
(50, 'Richard Marquand', 'img/generica.png', 49, NULL, 'UK', 'N', 'S', 'Hombre'),
(51, 'Luc Besson', 'img/generica.png', 64, NULL, 'Francia', 'N', NULL, 'Hombre'),
(52, 'Chuck Russell', 'img/generica.png', 65, NULL, 'USA', 'N', NULL, 'Hombre'),
(53, 'Sam Weisman', 'img/generica.png', 75, NULL, 'USA', 'N', NULL, 'Hombre'),
(54, 'Clint Eastwood', 'img/generica.png', 93, NULL, 'USA', 'S', NULL, 'Hombre'),
(55, 'Zack Snyder', 'img/generica.png', 57, NULL, 'USA', 'N', NULL, 'Hombre'),
(56, 'Noam Murro', 'img/generica.png', 62, NULL, 'Israel', 'N', NULL, 'Hombre'),
(57, 'Robert Zemeckis', 'img/generica.png', 71, NULL, 'USA', 'S', NULL, 'Hombre'),
(58, 'John Carpenter', 'img/generica.png', 75, NULL, 'USA', 'N', NULL, 'Hombre'),
(59, 'Patty Jenkins', 'img/generica.png', 51, NULL, 'USA', 'N', NULL, 'Mujer'),
(60, 'Ralph Nelson', 'img/generica.png', 71, NULL, 'USA', 'N', 'S', 'Hombre'),
(61, 'James Wan', 'img/generica.png', 46, NULL, 'Malasia', 'N', NULL, 'Hombre'),
(62, 'Andy Muschietti', 'img/generica.png', 49, NULL, 'Argentina', 'N', NULL, 'Hombre'),
(63, 'Joe Johnston', 'img/generica.png', 73, NULL, 'USA', 'S', NULL, 'Hombre'),
(64, 'Anthony Russo', 'img/generica.png', 53, NULL, 'USA', 'N', NULL, 'Hombre'),
(65, 'Joe Russo', 'img/generica.png', 52, NULL, 'USA', 'N', NULL, 'Hombre'),
(66, 'Jon Favreau', 'img/generica.png', 57, NULL, 'USA', 'N', NULL, 'Hombre'),
(67, 'Matthew Vaughn', 'img/generica.png', 52, NULL, 'UK', 'N', NULL, 'Hombre'),
(68, 'Sergey Bodrov', 'img/generica.png', 75, NULL, 'Rusia', 'N', 'S', 'Hombre'),
(69, 'Roar Uthaug', 'img/generica.png', 50, NULL, 'Noruega', 'N', NULL, 'Hombre'),
(70, 'Christian Rivers', 'img/generica.png', 49, NULL, 'Nueva Zelanda', 'S', NULL, 'Hombre'),
(71, 'Jordan Vogt-Roberts', 'img/generica.png', 39, NULL, 'USA', 'N', NULL, 'Hombre'),
(72, 'Anna Boden', 'img/generica.png', 44, NULL, 'USA', 'N', NULL, 'Mujer'),
(73, 'Rob Reiner', 'img/generica.png', 76, NULL, 'USA', 'N', NULL, 'Hombre'),
(74, 'Simon Wincer', 'img/generica.png', 80, NULL, 'Australia', 'N', NULL, 'Hombre'),
(75, 'Andrew Stanton', 'img/generica.png', 58, NULL, 'USA', 'S', NULL, 'Hombre'),
(76, 'Duncan Jones', 'img/generica.png', 52, NULL, 'UK', 'N', NULL, 'Hombre'),
(77, 'Gavin Hood', 'img/generica.png', 60, NULL, 'Sudáfrica', 'S', NULL, 'Hombre'),
(78, 'Peter Berg', 'img/generica.png', 59, NULL, 'USA', 'N', NULL, 'Hombre'),
(79, 'Martin Scorsese', 'img/generica.png', 80, NULL, 'Italia', 'S', NULL, 'Hombre'),
(80, 'Roland Emmerich', 'img/generica.png', 67, NULL, 'Alemania', 'N', NULL, 'Hombre'),
(81, 'John Sturges', 'img/generica.png', 82, NULL, 'USA', 'N', 'S', 'Hombre'),
(82, 'Mike Hodges', 'img/generica.png', 90, NULL, 'UK', 'N', 'S', 'Hombre'),
(83, 'Michael Anderson', 'img/generica.png', 98, NULL, 'UK', 'S', 'S', 'Hombre'),
(84, 'Simon Wells', 'img/generica.png', 62, NULL, 'USA', 'N', NULL, 'Hombre'),
(85, 'George Pal', 'img/generica.png', 72, NULL, 'USA', 'S', 'S', 'Hombre'),
(86, 'William Wyler', 'img/generica.png', 79, NULL, 'USA', 'S', 'S', 'Hombre'),
(87, 'Taika Waititi', 'img/generica.png', 47, NULL, 'Nueva Zelanda', 'S', NULL, 'Hombre'),
(88, 'John Hughes', 'img/generica.png', 59, NULL, 'USA', 'N', 'S', 'Hombre'),
(89, 'Richard Fleischer', 'img/generica.png', 89, NULL, 'USA', 'S', 'S', 'Hombre'),
(90, 'Fred M. Wilcox', 'img/generica.png', 56, NULL, 'USA', 'N', 'S', 'Hombre'),
(91, 'Marcus Nispel', 'img/generica.png', 60, NULL, 'Alemania', 'N', NULL, 'Hombre'),
(92, 'Lawrence Kasdan', 'img/generica.png', 74, NULL, 'USA', 'N', NULL, 'Hombre'),
(93, 'Sergio Leone', 'img/generica.png', 60, NULL, 'Italia', 'N', 'S', 'Hombre'),
(94, 'Delmer Daves', 'img/generica.png', 73, NULL, 'USA', 'N', 'S', 'Hombre'),
(95, 'David F. Sandberg', 'img/generica.png', 42, NULL, 'Suecia', 'N', NULL, 'Hombre'),
(96, 'Jaume Collet-Serra', 'img/generica.png', 49, NULL, 'España', 'N', NULL, 'Hombre'),
(97, 'J.J. Abrams', 'img/generica.png', 57, NULL, 'USA', 'N', NULL, 'Hombre'),
(98, 'Justin Lin', 'img/generica.png', 50, NULL, 'Taiwán', 'N', NULL, 'Hombre'),
(99, 'Alex Kurtzman', 'img/generica.png', 50, NULL, 'USA', 'N', NULL, 'Hombre'),
(100, 'Michael Bay', 'img/generica.png', 58, NULL, 'USA', 'N', NULL, 'Hombre'),
(101, 'Peyton Reed', 'img/generica.png', 59, NULL, 'USA', 'N', NULL, 'Hombre'),
(102, 'Mike Newell', 'img/generica.png', 81, NULL, 'UK', 'N', NULL, 'Hombre'),
(103, 'Howard Deutch', 'img/generica.png', 72, NULL, 'USA', 'N', NULL, 'Hombre'),
(104, 'Roger Michell', 'img/generica.png', 65, NULL, 'UK', 'N', NULL, 'Hombre'),
(105, 'Iain Softley', 'img/generica.png', 66, NULL, 'UK', 'N', NULL, 'Hombre'),
(106, 'Marc Lawrence', 'img/generica.png', 63, NULL, 'USA', 'N', NULL, 'Hombre'),
(107, 'Scott Derrickson', 'img/generica.png', 57, NULL, 'USA', 'N', NULL, 'Hombre'),
(108, 'Desmond Davis', 'img/generica.png', 97, NULL, 'UK', 'N', NULL, 'Hombre'),
(109, 'Louis Leterrier', 'img/generica.png', 50, NULL, 'Francia', 'N', NULL, 'Hombre'),
(110, 'Jonathan Liebesman', 'img/generica.png', 47, NULL, 'Sudáfrica', 'N', NULL, 'Hombre'),
(111, 'Tarsem Singh', 'img/generica.png', 62, NULL, 'India', 'N', NULL, 'Hombre'),
(112, 'Renny Harlin', 'img/generica.png', 64, NULL, 'Finlandia', 'N', NULL, 'Hombre'),
(113, 'Neil Burger', 'img/generica.png', 60, NULL, 'USA', 'N', NULL, 'Hombre'),
(114, 'Nicolas Winding Refn', 'img/generica.png', 52, NULL, 'Dinamarca', 'N', NULL, 'Hombre'),
(115, 'Tomasz Bagiński', 'img/generica.png', 47, NULL, 'Polonia', 'N', NULL, 'Hombre'),
(116, 'Victor Fleming', 'img/generica.png', 59, NULL, 'USA', 'S', 'S', 'Hombre'),
(117, 'Ben Stiller', 'img/generica.png', 58, NULL, 'USA', 'N', NULL, 'Hombre'),
(118, 'Don Chaffey', 'img/generica.png', 73, NULL, 'UK', 'N', 'S', 'Hombre'),
(119, 'Dean DeBlois', 'img/generica.png', 53, NULL, 'Canadá', 'N', NULL, 'Hombre'),
(120, 'Gareth Edwards', 'img/generica.png', 48, NULL, 'UK', 'N', NULL, 'Hombre'),
(121, 'Matthew Robbins', 'img/generica.png', 78, NULL, 'USA', 'N', NULL, 'Hombre'),
(122, 'Greta Gerwig', 'img/generica.png', 39, NULL, 'USA', 'N', NULL, 'Mujer'),
(123, 'Michael Mann', 'img/generica.png', 80, NULL, 'USA', 'N', NULL, 'Hombre'),
(124, 'Rob Bowman', 'img/generica.png', 63, NULL, 'USA', 'N', NULL, 'Hombre'),
(125, 'Enrique Gato', 'img/generica.png', 46, NULL, 'España', 'N', NULL, 'Hombre'),
(126, 'Rian Johnson', 'img/generica.png', 49, NULL, 'USA', 'N', NULL, 'Hombre'),
(127, 'John Musker', 'img/generica.png', 69, NULL, 'USA', 'N', NULL, 'Hombre'),
(128, 'Herbert Ross', 'img/generica.png', 74, NULL, 'USA', 'N', NULL, 'Hombre'),
(129, 'Craig Brewer', 'img/generica.png', 52, NULL, 'USA', 'N', NULL, 'Hombre'),
(130, 'Brett Ratner', 'img/generica.png', 54, NULL, 'USA', 'N', NULL, 'Hombre'),
(131, 'Richard Curtis', 'img/generica.png', 67, NULL, 'Nueva Zelanda', 'N', NULL, 'Hombre'),
(132, 'Alfred Hitchcock', 'img/generica.png', 80, NULL, 'UK', 'S', 'S', 'Hombre'),
(133, 'Paul Schneider', 'img/generica.png', 1, NULL, 'Desconocido', 'N', NULL, 'Hombre'),
(134, 'Paul King', 'img/generica.png', 45, NULL, 'UK', 'N', NULL, 'Hombre'),
(135, 'Will Gluck', 'img/generica.png', 45, NULL, 'USA', 'N', NULL, 'Hombre'),
(136, 'Stephen Merchant', 'img/fotos/directores/director_stephen.jpg', 49, '1974-11-24', 'UK', 'N', 'N', 'Hombre'),
(137, 'Sam Taylor-Johnson', 'img/fotos/directores/director_sam_taylor.jpg ', 57, '1967-03-04', 'UK', 'N', 'N', 'Mujer');
