
--
-- Volcado de datos para la tabla `actores`
--

INSERT INTO `actores` (`pk_id_actor`, `nombre_actor`, `foto_actor`, `edad_actor`, `fecha_nacimiento_actor`, `nacionalidad_actor`, `oscar`, `actor_fallecido`) VALUES
(1, 'Robert de Niro', 'img/generica.png', 79, NULL, 'USA', 'S', NULL),
(2, 'Harrison Ford', 'img/generica.png', 80, NULL, 'USA', 'N', NULL),
(3, 'Tom Cruise', 'img/generica.png', 60, NULL, 'USA', 'N', NULL),
(4, 'Chris Pine', 'img/generica.png', 42, NULL, 'USA', 'N', NULL),
(5, 'Javier Bardem', 'img/generica.png', 54, NULL, 'España', 'S', NULL),
(6, 'Antonio Banderas', 'img/generica.png', 62, NULL, 'España', 'N', NULL),
(7, 'Santiago Segura', 'img/generica.png', 56, NULL, 'España', 'N', NULL),
(8, 'Michael Fassbender', 'img/generica.png', 46, NULL, 'Alemania', 'N', NULL),
(9, 'Robert Downey Jr.', 'img/generica.png', 58, NULL, 'USA', 'N', NULL),
(10, 'John Wayne', 'img/generica.png', 72, NULL, 'USA', 'S', 'S'),
(11, 'Viggo Mortensen', 'img/generica.png', 64, NULL, 'USA', 'N', NULL),
(12, 'Elijah Wood', 'img/generica.png', 42, NULL, 'USA', 'N', NULL),
(13, 'Pierce Brosnan', 'img/generica.png', 70, NULL, 'Irlanda', 'N', NULL),
(14, 'Edward Fox', 'img/generica.png', 86, NULL, 'UK', 'N', 'N'),
(15, 'Eneko Sagardoy Mujika', 'img/generica.png', 29, NULL, 'España', 'N', NULL),
(16, 'Patrick Gibson', 'img/generica.png', 28, NULL, 'Irlanda', 'N', NULL),
(17, 'Daniel Craig', 'img/generica.png', 55, NULL, 'UK', 'N', NULL),
(18, 'Matt Damon', 'img/generica.png', 52, NULL, 'USA', 'N', NULL),
(19, 'Sharlto Copley', 'img/generica.png', 49, NULL, 'Sudáfrica', 'N', NULL),
(20, 'Martin Freeman', 'img/generica.png', 51, NULL, 'UK', 'N', NULL),
(21, 'Peter O\'Toole', 'img/generica.png', 81, NULL, 'UK', 'S', 'S'),
(22, 'Mark Wahlberg', 'img/generica.png', 52, NULL, 'USA', 'N', NULL),
(23, 'Christian Bale', 'img/generica.png', 49, NULL, 'UK', 'S', NULL),
(24, 'Robert Pattinson', 'img/generica.png', 37, NULL, 'UK', 'N', NULL),
(25, 'Sam Worthington', 'img/generica.png', 46, NULL, 'Australia', 'N', NULL),
(26, 'Tobey Maguire', 'img/generica.png', 47, NULL, 'USA', 'N', NULL),
(27, 'Paul Newman', 'img/generica.png', 83, NULL, 'USA', 'S', 'S'),
(28, 'Robin Williams', 'img/generica.png', 63, NULL, 'USA', 'S', 'S'),
(29, 'Val Kilmer', 'img/generica.png', 63, NULL, 'USA', 'N', NULL),
(30, 'Arnold Schwarzenegger', 'img/generica.png', 75, NULL, 'Austria', 'N', NULL),
(31, 'Alexander Skarsgård', 'img/generica.png', 46, NULL, 'Suecia', 'N', NULL),
(32, 'Christopher Reeve', 'img/generica.png', 52, NULL, 'USA', 'N', 'S'),
(33, 'Josh Brolin', 'img/generica.png', 55, NULL, 'USA', 'N', NULL),
(34, 'Sylvester Stallone', 'img/generica.png', 76, NULL, 'USA', 'N', NULL),
(35, 'Armie Hammer', 'img/generica.png', 36, NULL, 'USA', 'N', NULL),
(36, 'Kevin Costner', 'img/generica.png', 68, NULL, 'USA', 'S', NULL),
(37, 'Marc Singer', 'img/generica.png', 75, NULL, 'Canadá', 'N', NULL),
(38, 'Clive Owen', 'img/generica.png', 59, NULL, 'UK', 'N', NULL),
(39, 'Charlie Hunnam', 'img/generica.png', 43, NULL, 'UK', 'N', NULL),
(40, 'Chris Hemsworth', 'img/generica.png', 39, NULL, 'Australia', 'N', NULL),
(41, 'Christopher Lambert', 'img/generica.png', 66, NULL, 'USA', 'N', NULL),
(42, 'Michael Douglas', 'img/generica.png', 78, NULL, 'USA', 'S', NULL),
(43, 'Timothée Chalamet', 'img/generica.png', 27, NULL, 'Francia', 'N', NULL),
(44, 'Brendan Fraser', 'img/generica.png', 55, NULL, 'USA', 'S', NULL),
(45, 'Bruce Willis', 'img/generica.png', 68, NULL, 'USA', 'N', NULL),
(46, 'Dwayne Johnson', 'img/generica.png', 51, NULL, 'USA', 'N', NULL),
(47, 'Jim Carrey', 'img/generica.png', 61, NULL, 'Canadá', 'N', NULL),
(48, 'Clint Eastwood', 'img/generica.png', 93, NULL, 'USA', 'S', NULL),
(49, 'Patrick Wilson', 'img/generica.png', 50, NULL, 'USA', 'N', NULL),
(50, 'Gerard Butler', 'img/generica.png', 53, NULL, 'UK', 'N', NULL),
(51, 'Sullivan Stapleton', 'img/generica.png', 46, NULL, 'Australia', 'N', NULL),
(52, 'Michael J. Fox', 'img/generica.png', 62, NULL, 'USA', 'N', NULL),
(53, 'Kurt Russell', 'img/generica.png', 72, NULL, 'USA', 'N', NULL),
(54, 'Henry Cavill', 'img/generica.png', 40, NULL, 'UK', 'N', NULL),
(55, 'Cary Grant', 'img/generica.png', 82, NULL, 'UK', 'N', 'S'),
(56, 'Ryan Reynolds', 'img/generica.png', 46, NULL, 'Canadá', 'N', NULL),
(57, 'Hugh Jackman', 'img/generica.png', 55, NULL, 'Australia', 'N', NULL),
(58, 'Jason Momoa', 'img/generica.png', 44, NULL, 'USA', 'N', NULL),
(59, 'Ezra Miller', 'img/generica.png', 30, NULL, 'USA', 'N', NULL),
(60, 'Chris Evans', 'img/generica.png', 42, NULL, 'USA', 'N', NULL),
(61, 'Kenneth Branagh', 'img/generica.png', 63, NULL, 'UK', 'S', NULL),
(62, 'Charlie Cox', 'img/generica.png', 40, NULL, 'UK', 'N', NULL),
(63, 'Jeff Bridges', 'img/generica.png', 73, NULL, 'USA', 'S', NULL),
(64, 'Dominic West', 'img/generica.png', 53, NULL, 'UK', 'N', NULL),
(65, 'Hugo Weaving', 'img/generica.png', 63, NULL, 'UK', 'N', NULL),
(66, 'Tom Hiddleston', 'img/generica.png', 42, NULL, 'UK', 'N', NULL),
(67, 'Samuel L. Jackson', 'img/generica.png', 74, NULL, 'USA', 'S', NULL),
(68, 'Cary Elwes', 'img/generica.png', 60, NULL, 'UK', 'N', NULL),
(69, 'Alec Baldwin', 'img/generica.png', 65, NULL, 'USA', 'N', NULL),
(70, 'Bill Campbell', 'img/generica.png', 64, NULL, 'USA', 'N', NULL),
(71, 'Billy Zane', 'img/generica.png', 57, NULL, 'USA', 'N', NULL),
(72, 'Garrett Hedlund', 'img/generica.png', 39, NULL, 'USA', 'N', NULL),
(73, 'Taylor Kitsch', 'img/generica.png', 42, NULL, 'Canadá', 'N', NULL),
(74, 'Travis Fimmel', 'img/generica.png', 43, NULL, 'Australia', 'N', NULL),
(75, 'Asa Butterfield', 'img/generica.png', 26, NULL, 'UK', 'N', NULL),
(77, 'Will Smith', 'img/generica.png', 54, NULL, 'USA', 'S', NULL),
(78, 'Jeff Goldblum', 'img/generica.png', 70, NULL, 'USA', 'N', NULL),
(79, 'Yul Brynner', 'img/generica.png', 65, NULL, 'Suiza', 'S', 'S'),
(80, 'Denzel Washington', 'img/generica.png', 69, NULL, 'USA', 'S', NULL),
(81, 'Sam J. Jones', 'img/generica.png', 68, NULL, 'USA', 'N', NULL),
(82, 'David Niven', 'img/generica.png', 73, NULL, 'UK', 'S', 'S'),
(83, 'Guy Pearce', 'img/generica.png', 56, NULL, 'Australia', 'N', NULL),
(84, 'Rod Taylor', 'img/generica.png', 84, NULL, 'USA', 'N', 'S'),
(85, 'Gregory Peck', 'img/generica.png', 87, NULL, 'USA', 'S', 'S'),
(86, 'Matthew Broderick', 'img/generica.png', 61, NULL, 'USA', 'N', NULL),
(87, 'Walter Pidgeon', 'img/generica.png', 87, NULL, 'Canadá', 'N', 'S'),
(88, 'Karl Urban', 'img/generica.png', 51, NULL, 'Nueva Zelanda', 'N', NULL),
(89, 'Gary Cooper', 'img/generica.png', 60, NULL, 'USA', 'S', 'S'),
(90, 'Ben Affleck', 'img/generica.png', 50, NULL, 'USA', 'S', NULL),
(91, 'Zachary Levi', 'img/generica.png', 43, NULL, 'USA', 'N', NULL),
(92, 'Taron Egerton', 'img/generica.png', 33, NULL, 'UK', 'N', NULL),
(93, 'Ewan McGregor', 'img/generica.png', 52, NULL, 'UK', 'N', NULL),
(94, 'Paul Rudd', 'img/generica.png', 54, NULL, 'USA', 'N', NULL),
(95, 'Hugh Grant', 'img/generica.png', 63, NULL, 'UK', 'N', NULL),
(96, 'Jake Gyllenhaal', 'img/generica.png', 42, NULL, 'USA', 'N', NULL),
(97, 'Keanu Reeves', 'img/generica.png', 58, NULL, 'Canadá', 'N', NULL),
(98, 'Benedict Cumberbatch', 'img/generica.png', 46, NULL, 'UK', 'N', NULL),
(99, 'Harry Hamlin', 'img/generica.png', 71, NULL, 'USA', 'N', NULL),
(101, 'Matthew Modine', 'img/generica.png', 64, NULL, 'USA', 'N', NULL),
(102, 'Edward Norton', 'img/generica.png', 53, NULL, 'USA', 'N', NULL),
(103, 'Mark Ruffalo', 'img/generica.png', 55, NULL, 'USA', 'N', NULL),
(104, 'Bradley Cooper', 'img/generica.png', 48, NULL, 'USA', 'N', NULL),
(105, 'Oscar Isaac', 'img/generica.png', 44, NULL, 'USA', 'N', NULL),
(106, 'Ryan Gosling', 'img/generica.png', 42, NULL, 'Canadá', 'N', NULL),
(107, 'Mackenyu Arata', 'img/generica.png', 26, NULL, 'USA', 'N', NULL),
(108, 'James Franco', 'img/generica.png', 45, NULL, 'USA', 'N', NULL),
(110, 'Frank Morgan', 'img/generica.png', 59, NULL, 'USA', 'N', 'S'),
(111, 'Ben Stiller', 'img/generica.png', 58, NULL, 'USA', 'N', NULL),
(112, 'Liam Neeson', 'img/generica.png', 71, NULL, 'UK', 'N', NULL),
(113, 'Todd Armstrong', 'img/generica.png', 55, NULL, 'USA', 'N', 'S'),
(114, 'Kellan Lutz', 'img/generica.png', 38, NULL, 'USA', 'N', NULL),
(115, 'Sin actor', NULL, NULL, NULL, '', NULL, NULL),
(116, 'Tye Sheridan', 'img/generica.png', 27, NULL, 'USA', 'N', NULL),
(117, 'John David Washington', 'img/generica.png', 38, NULL, 'USA', 'N', NULL),
(118, 'Peter MacNicol', 'img/generica.png', 69, NULL, 'USA', 'N', NULL),
(119, 'Daniel Day-Lewis', 'img/generica.png', 66, NULL, 'Irlanda', 'S', NULL),
(120, 'Hayden Christensen', 'img/generica.png', 42, NULL, 'Canadá', 'N', NULL),
(121, 'Adam Driver', 'img/generica.png', 40, NULL, 'USA', 'N', NULL),
(122, 'Kevin Bacon', 'img/generica.png', 65, NULL, 'USA', 'N', NULL),
(123, 'Kenny Wormald', 'img/generica.png', 39, NULL, 'USA', 'N', NULL),
(124, 'Joel Courtney', 'img/generica.png', 27, NULL, 'USA', 'N', NULL),
(125, 'Russell Crowe', 'img/generica.png', 59, NULL, 'Nueva Zelanda', 'S', NULL),
(126, 'Brian Bloom', 'img/generica.png', 53, NULL, 'USA', 'N', NULL),
(127, 'Lee Van Cleef', 'img/fotos/actores/Lee_Van_Cleef.jpg', 64, NULL, 'USA', 'N', 'S'),
(128, 'John Cena', 'img/generica.png', 46, NULL, 'USA', 'N', 'N'),
(129, 'Idris Elba', 'img/generica.png', 51, NULL, 'UK', 'N', 'N'),
(130, 'Glen Powell', 'img/generica.png', 35, NULL, 'USA', 'N', NULL),
(131, 'Sylvester Stallone', 'img/generica.png', 77, NULL, 'USA', 'N', NULL),
(134, 'Logan Lerman', 'img/fotos/actores/actor_logan.jpg', 32, '1992-01-19', 'USA', 'S', 'N'),
(136, 'Steve Carell', 'img/fotos/actores/actor_steve.jpg', 61, '1962-08-16', 'USA', 'N', 'N'),
(137, 'John Krasinski', 'img/fotos/actores/actor_john.png', 44, '1979-10-20', 'USA', 'N', 'N'),
(139, 'Eddie Marsan', 'img/fotos/actores/actor_eddie.jpg', 56, '1968-06-09', 'UK', 'N', 'N');
